#                                                           Developed by Ruben_Artz
#
#                                                     (PLAY.STN-STUDIOS.COM @ (C) 2018-2022)

name: 'LobbyHeadItem'
version: '${version}'
main: 'ruben_artz.lobby.Lobby'
authors: [ 'Ruben_Artz', 'STN Studios' ]
softdepend: [ 'PlaceholderAPI' ]
website: 'https://www.spigotmc.org/resources/62507/'
description: 'Show the head of the game in the lobby!'
api-version: '1.16'

commands:
  lobbyheaditem:
    description: 'Main command of this plugin.'
    aliases: [ 'lob' ]