#                                                           Developed by Ruben_Artz
#
#                                                     (MC.ARTZSTUDIO.DEV @ (C) 2018-2026)

name: 'LobbyHeadItem'
version: '${version}'
main: 'artzstudio.dev.lobby.spigot.Lobby'
authors: [ 'Ruben_Artz', 'Artz Studio' ]
softdepend: [ 'PlaceholderAPI' ]
website: 'https://www.spigotmc.org/resources/62507/'
description: 'Show the head of the game in the lobby!'
api-version: '1.16'

commands:
  lobbyheaditem:
    description: 'Main command of this plugin.'
    aliases: [ 'lob' ]